name: Deploy Frontend (prod)

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/deploy-frontend-shared.yml
    with:
      tfc_workspace: ${{ vars.TFC_WORKSPACE_PROD }}
      api_stage: prod
    secrets: inherit
